name: "Config Update"

on:
https://github.com/resasanian/Mirza  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: mozafarsekaloo/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php main.php
          git config --global user.email "mozafarsekaloo@yahoo.com"
          git config --global user.name "mozafarsekaloo"
          git config credential.helper store
          git add -A
          git commit -m "ðŸš€ Config Update - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
